### ISSUE TITLE
Parity error

### ISSUE THREAD

**Issue by cashbit** [silentmatt/js-expression-eval#40]
Hi, trying to evaluate:

10/-1 gives a parity error.

It solves, this way:

10/(-1)

**Comment by rreusser** [comment]
Looks like it's failing to convert to RPN correctly, which is probably related to an unhandled unary `-` corner case. Compare the tokens for this example that works:

```
[ Token { type_: 0, index_: 0, prio_: 0, number_: 10 },
  Token { type_: 0, index_: 0, prio_: 0, number_: 1 },
  Token { type_: 1, index_: '-', prio_: 151, number_: 0 },
  Token { type_: 2, index_: '/', prio_: 52, number_: 0 } ]
      ✓ 10/(-1)
```

To the tokens for the example that fails:

```
[ Token { type_: 0, index_: 0, prio_: 0, number_: 10 },
  Token { type_: 2, index_: '/', prio_: 52, number_: 0 },
  Token { type_: 0, index_: 0, prio_: 0, number_: 1 },
  Token { type_: 1, index_: '-', prio_: 51, number_: 0 } ]
      1) 10/(-1)
```

**Comment by mcrumley-vology** [comment]
I think the problem is on [line 588](https://github.com/silentmatt/js-expression-eval/blob/master/parser.js#L588), where it sets the priority to 2. It should probably be 5 like the other unary operators, unless there's a reason for it being 2 that I forgot about.

I did a quick test for this case, and that fixed it, but I'll need to do more tests make sure it doesn't break something else.

**Comment by rreusser** [comment]
Thanks for the reply and the suggestion! That fixes the unary `-` issues (see additional test cases [here](https://github.com/rreusser/js-expression-eval/blob/pre-merge/test/parserSpec.js#L38-L68)) but causes `Parser.evaluate("-3^x", {x: 4})` to equal `81` instead of `-81`.

I'm not really up to speed on parsers, so I'm struggling a bit, but here's my current understanding about how it works: This parser sets `expected` to try to disambiguate the correct interpretation of unary `-`. It builds up a token stack. Sometimes it sets `noperators += 2;`. Does that make it an [LR(1)](https://en.wikipedia.org/wiki/Canonical_LR_parser) parser that looks as much as one token ahead to see what things mean?

If that's the case, does that mean everything here is fundamentally solid and it's just a matter of adding failing test cases and messing with the logic until it's all good? 😄

**Comment by rreusser** [comment]
(I might not be right about that… your code + this fix appears cleaner and closer than the fork I was working with, so there's maybe some progress to be made here debugging… I'll work on this and see if I can come up with something)

**Comment by rreusser** [comment]
That single fix (on the master branch) gives a single failing test — which appears otherwise valid in terms of RPN, so looking to priorities…

```
[ Token { type_: 0, index_: 0, prio_: 0, number_: 3 },
  Token { type_: 1, index_: '-', prio_: 5, number_: 0 },
  Token { type_: 3, index_: 'x', prio_: 0, number_: 0 } 
  Token { type_: 2, index_: '^', prio_: 5, number_: 0 } ] 
      1) -3^x
```

**Comment by rreusser** [comment]
That single fix on the master branch gives this, which isn't quite right:

```
[ Token { type_: 0, index_: 0, prio_: 0, number_: 3 },
  Token { type_: 1, index_: '-', prio_: 5, number_: 0 },
  Token { type_: 3, index_: 'x', prio_: 0, number_: 0 } 
  Token { type_: 2, index_: '^', prio_: 5, number_: 0 } ] 
      1) -3^x
```

It should be `3 x ^ -` instead of `3 - x ^`, right?

**Comment by silentmatt** [comment]
Yes, that's correct, so apparently it is a little more complicated than that. Looking at it more, I think the reason it has a lower precedence than the the other unary operators is so that an expression like `-x^2` parses as `-(x^2)`, but `sqrt(x)^2` is `(sqrt(x))^2`. So bumping the `^` operator up to 6, and having the `isOp1` and `isOp2` functions set `tokenprio = 7` might be the way to go.

**Comment by silentmatt** [comment]
Also to (kind of) answer your question about it being an LR(1) parser, it's based on the shunting yard algorithm, which I think is equivalent to an LR(1) parser, but it's not really a direct translation. It's been awhile since I've taken a computer science class though, so don't take any of that as absolute truth :)

**Comment by rreusser** [comment]
All good. This makes sense. Every ad hoc parser I've ever written has turned out very badly and looked like some of the forks + fixes were headed (maybe) into ad hoc land, so was just trying to pin down the formalities and convince myself maybe it's just the parameters (precedences, operators) that need modification and not a bunch of random flags and conditions. 😄
