### ISSUE TITLE
What is the security like for this library?

### ISSUE THREAD

**Issue by z0u** [silentmatt/js-expression-eval#44]
`README.md` says:

> There’s no security risk currently, because you can only run code in your own browser

What does this mean?

- Can an expression have any side effects? Suppose I'm not passing in any custom functions
- To your knowledge, is it safe to evaluate a user-supplied expression? Can user B safely run user A's expression in their browser?

**Comment by silentmatt** [comment]
That sentence was referring to my specific use case (an online function plotter), which doesn't have any features that allow you to, for instance, send someone a link with code to run. The readme came from my the description on the site where that hopefully made more sense. I should definitely change that since the context isn't as clear.

However, as far as I know, it's safe to run user-supplied expressions as long as you don't add any functions with security implications. That's assuming a "clean" environment where you haven't messed with any built-in functions, prototypes, etc.

**Comment by buremba** [comment]
@silentmatt specifically, can it access the `window` variable in any way? Also, If you pass a javascript object to the scope, it also raises a security problem. For example, it's trivial to access to internal representation of `Math` object with `Math.__proto__.constructor`.

**Comment by silentmatt** [comment]
@buremba There shouldn't be a way to access the `window` variable, or anything else that you don't explicitly give it access to via the scope parameter. So as long as you're not adding unsafe custom functions, or passing them into the scope parameter, you can't run arbitrary code, or access the JavaScript scope.

If you want to be extra cautious, you can also disable the `.` operator by constructing the parser instance with `new Parser({ allowMemberAccess: false });`. Of course, that's not an option if you need to support objects in your expressions. In that case, just be careful about what you include in the scope.

So the TL;DR version is, arbitrary expressions should be safe to run by default, but it won't protect you from yourself if you add holes using JavaScript.

**Comment by buremba** [comment]
Cool, I think that it would be great to have a dedicated section in README. Thanks for this great library! 💪
